const cheerio=require('cheerio');const {esc}=require('./cms-content.cjs');
function designNeonPage(html,p){
 const $=cheerio.load(html);$('body').addClass('neon-page');$('head').append('<link rel="stylesheet" href="/assets/neon-cdmx.css"><script defer src="/assets/neon-cdmx.js"></script>');
 $('.hero').replaceWith(`<section class="neon-hero" aria-labelledby="neon-title"><div class="neon-copy"><p class="neon-city">Tu próxima fiesta empieza en CDMX</p><h1 id="neon-title">${esc(p.title.replace(/_+$/,''))}</h1><p class="neon-intro">Lentes, pulseras y accesorios luminosos para dejarlo todo en la pista. Elige tus colores. Nosotros ponemos los detalles.</p><div class="neon-actions"><a href="#productos" class="neon-buy">Arma tu fiesta <span aria-hidden="true">↗</span></a><a href="#promociones" class="neon-packages">Explorar paquetes</a></div><div class="neon-local"><span aria-hidden="true">⌖</span><span>Encuéntranos en Portales<br><strong>Rumania 613 · Benito Juárez</strong></span></div></div><div class="neon-stage"><span class="neon-word" aria-hidden="true">NEÓN</span><figure><img class="neon-before" src="/img/cms/neon-before.jpg" alt="Las mismas tres personas sin pintura ni iluminación neón" width="1536" height="1024" fetchpriority="high"><img class="neon-after" aria-hidden="true" src="/img/cms/94d6f367e829967d.jpg" alt="Personas con maquillaje fluorescente y accesorios neón bajo luz ultravioleta" width="960" height="640" fetchpriority="high"><figcaption>Una foto. Dos ambientes.</figcaption></figure><button class="neon-switch" type="button" aria-pressed="false"><span class="neon-switch-dot" aria-hidden="true"></span><span>Enciende el ambiente</span></button></div></section><div class="neon-ribbon" aria-label="Opciones para tu fiesta"><span>Pulseras que brillan</span><span>Lentes con actitud</span><span>Detalles para todos</span><a href="#productos">Encuentra tu color ↓</a></div>`);
 $('.source-content').remove();
 $('.cms-categories').remove();
 $('#productos .section-heading').html('<div><p class="neon-kicker">Elige lo que va contigo</p><h2>Pequeños detalles.<br>Una fiesta enorme.</h2></div><p class="neon-section-note">Combina tus favoritos y agrégalos al carrito.<br>Puedes empezar desde una pieza.</p>');
 $('#productos').before(`<section class="neon-guide wrap" aria-labelledby="neon-guide-title"><div><h2 id="neon-guide-title">No todo brilla<br>de la misma manera.</h2><p>Elige los accesorios según la iluminación de tu evento.</p></div><div class="neon-guide-items"><article><span class="neon-swatch swatch-uv" aria-hidden="true"></span><h3>Color fluorescente</h3><p>Destaca bajo luz ultravioleta. Revisa en cada ficha si el artículo necesita luz UV.</p></article><article><span class="neon-swatch swatch-glow" aria-hidden="true"></span><h3>Luz propia</h3><p>Explora accesorios luminosos y verifica su activación, duración y contenido en la ficha.</p></article></div></section>`);
 $('.reviews').remove(); // Do not attach generic copied testimonials to an unverified city.
 $('#ubicacion').addClass('neon-location');$('#ubicacion .section-kicker').text('De la pantalla a tu fiesta');$('#ubicacion h2').text('Ven por el color.');
 $('#promotions-title').text('La fiesta, en paquete.');
 $('#cms-promo-products').before('<p class="neon-package-note">Compara los paquetes neón. Consulta el contenido y precio actual en cada ficha.</p>');
 $('.related-pages').remove();
 $('meta[name="description"],meta[property="og:description"]').attr('content','Artículos neón para fiestas en CDMX: pulseras, lentes, luminosos y paquetes. Compra por pieza o consulta mayoreo. Visítanos en Rumania 613, Portales.');
 $('script[type="application/ld+json"]').each((_,el)=>{const data=JSON.parse($(el).text());data.description=$('meta[name="description"]').attr('content');$(el).text(JSON.stringify(data).replace(/</g,'\\u003c'));});
 $('meta[property="og:image"]').attr('content','https://mifiestashop.vercel.app/img/cms/94d6f367e829967d.jpg');
 return $.html();
}
module.exports={designNeonPage};
